### ISSUE TITLE
Nbt stuff dont work on armorstands

### ISSUE THREAD

**Issue by JeroenoBoy** [ShaneBeee/Sk-NBeeT#10]
i tried to make custom items that lay on the ground, when i tried to do the pickup, the last broadcast line doesnt execute, aka the nbt tag didnt apply to the entity,

Skript ver: 2.4-alpha3
server version: git-paper-167 (implementet from spigot: 1.14.4-R0.1-SNAPSHOT)

code:
#spawning
```vb
spawn armor stand at {_loc1}
add "{CustomName:StickoStando}" to entity-nbt of last spawned armor stand
```

#right click stuff:
```vb
on right click:
    distance between player and target block is less than 2
    broadcast "start"
    loop all entities in radius 2 of target block:
        if "%loop-entity%" is "armor stand": #i know, but any other way it didnt work
            broadcast "armor mc standface"
            if nbt of loop-entity contains "{CustomName:StickoStando}":
                broadcast "lmao this works not"
```

[Debug results when i click near one](https://gyazo.com/a36d8c57a656f87202d03b81f082d47f)
no errors in the console nor on reload

**Comment by ShaneBeee** [comment]
I updated it to make it easier to read ;)

**Comment by JeroenoBoy** [comment]
im not good at github stuff xD

**Comment by ShaneBeee** [comment]
Seems to me that your NBT tag is wrong.
EX: I set the display name of an armor stand:
`!set display name of target entity to "&aBOB"`

Then when running:
`!send "NBT: %nbt of target entity%" to console`
this is the output section for the name:
```
CustomName:'{"extra":[{"color":"green","text":"BOB"}],"text":""}'
```

**Comment by JeroenoBoy** [comment]
but like the name should be hidden, and cant i like add my own nbt tags to a entity? like {gameEntity:1}

**Comment by ShaneBeee** [comment]
Im not sure, I dont actually know that much about the NBT tags themselves. 

This plugin literally does this:
- Takes a string
- Sends it to MojangsonParser to parse it into an NBT compound
- Applies this compound to the item/entity/tile entity

99.9% of errors are caused from incorrect NBT strings. 

in 1.13 Minecraft changed a bunch of their NBT stuff
