### ISSUE TITLE
file nbt

### ISSUE THREAD

**Issue by DDuart** [ShaneBeee/Sk-NBeeT#11]
Hi, can you add way to change nbt in `.dat` files?

https://github.com/Tuke-Nuke/SkStuff/blob/b9328a97bef7adf1ea59b148a4b1f523dd0ede1a/src/me/TheBukor/SkStuff/expressions/ExprFileNBT.java#L18

**Comment by ShaneBeee** [comment]
this has now been added in [**2.5.0**](https://github.com/ShaneBeee/Sk-NBeeT/releases/tag/2.5.0)

I have done very little testing on this, so please let me know if there are any issues.
