### ISSUE TITLE
NBT list too long for Skript - Make "Add NBT" to not replace the tag when it's a list.

### ISSUE THREAD

**Issue by Tai1er** [ShaneBeee/Sk-NBeeT#12]
Hello, I'm trying to add a list of blocks in the tag "CanPlaceOn" of an item but the string is too long for Skript.
When I try to split the list in two "add %string% to item-nbt of %item%", the first is deleted by the second.

Since there is already a "set" expression for items, why the "add" expression has the same effect and don't combine the old value and the new value of a tag when it's a list?

**Comment by ShaneBeee** [comment]
have you tried using the join expression?

**Comment by ShaneBeee** [comment]
Closing this due to no response.
