### ISSUE TITLE
Entities in Structures

### ISSUE THREAD

**Issue by Wealthyturtle** [ShaneBeee/Sk-NBeeT#17]
Hello, I was trying to spawn structures (with entities saved inside them) using Sk-NBeeT's ``load structure`` effect. However, it seems that the entities stored within structures do not get loaded. The blocks from the structure are loaded, but the entities are not. Perhaps you could add that as a feature? Thanks :)

**Comment by ShaneBeee** [comment]
Thats a great idea, I totally forgot structure blocks could save entities. 
I'll start working on that.

**Comment by ShaneBeee** [comment]
Added in latest release
https://github.com/ShaneBeee/Sk-NBeeT/releases/tag/2.8.0
