### ISSUE TITLE
custom name of inventory Not working as expected

### ISSUE THREAD

**Issue by ThePumpkin5822** [ShaneBeee/Sk-NBeeT#18]
I see in the docs on skripthub there a note under [custom name expression](https://skripthub.net/docs/?id=3751) stating skript's inventory name expression is broken. It also appears to be broken in Sk-NBeeT. Running the expression gives the same result as running the Skript expression.

Code:

```
on rightclick:
	message "%custom name of player's current inventory%"
	if custom name of player's current inventory = "Not crafting":
		message "Woohoo is worked"
```

Most (I didn't bother testing all) inventories will just output "Crafting".

Skript: 2.4 Stable
Sk-NBeeT: 2.7.3
Spigot: Built on 12/4/19

**Comment by ShaneBeee** [comment]
Thanks for letting me know.  
I’m not sure how it could have broken but i’ll test when I get home.

**Comment by ShaneBeee** [comment]
Ok I did some testing, this isn't actually an issue with SK-NBeeT, its just how events work.
Im not sure what you are clicking, but let's say you are clicking on a chest, the right click event is fired before the chest would actually open. Therefor the current inventory of the player **IS** their crafting inventory. 
If you add a 1 tick wait after the right click event, everything works fine.

**Comment by ThePumpkin5822** [comment]
Right... I've always hated quirks like this...

**Comment by ShaneBeee** [comment]
> Right... I've always hated quirks like this...

While I do agree sometimes it is a royal pain in the ass, it is done on purpose, for example, to allow us to cancel an event.
Bukkit has to fire the event before it actually happens, this way if we cancel it, bukkit will prevent the event from actually happening. 
It may seem odd, but logically it's the only way for it to work.
