### ISSUE TITLE
Nested NBT Tags

### ISSUE THREAD

**Issue by Wealthyturtle** [ShaneBeee/Sk-NBeeT#20]
Currently, as of Sk-NBeeT 2.9.0, there is no way to "cleanly" get a nested NBT tag's value. For example, in a Shulker Box's block, it has an NBT structure of ``{BlockEntityTag:{Items:[{Slot:0b...}]}}``. Currently, the only way to extract the ``Items`` NBT tag is to do something like ``(tag "Items" of (tag "BlockEntityTag" of {_nbt}))``, which is rather convoluted.

Instead, perhaps Sk-NBeeT could use some syntax similar to the /data command already present in Minecraft to extract nested NBT tags via ``tag "BlockEntityTag.Items"`` or something similar (see https://minecraft.gamepedia.com/Commands/data#Examples for more syntax examples)

**Comment by ShaneBeee** [comment]
Added in [**2.9.1**](https://github.com/ShaneBeee/Sk-NBeeT/releases/tag/2.9.1)
