### ISSUE TITLE
Nbt of ItemStack not work

### ISSUE THREAD

**Issue by Spartan9802** [ShaneBeee/Sk-NBeeT#21]
Good evening,
I really use a lot Skript mirror in my scripts and I noticed that "nbt of {__item}" doesn't work if it's a spigot ItemStack, it works with SkStuff on the other hand.
(My server is in 1.8.8)

Here is a functional example:
```
command /test:
	trigger:
		send "Work %item-nbt of player's tool%"
		
		set {_item} to player.getItemInHand()
		send "Dont Work %item-nbt of {_item}%"
```

**Comment by ShaneBeee** [comment]
Thanks for letting me know. I will take a look at this and fix that up.

**Comment by ShaneBeee** [comment]
I can not seem to replicate your issue:

<img width="873" alt="Screen Shot 2020-01-09 at 12 37 19 PM" src="https://user-images.githubusercontent.com/20008482/72102926-f1d9d400-32dc-11ea-9287-ad8811af22ff.png">

**Comment by Spartan9802** [comment]
Strange, what version of skript do you use?

**Comment by ShaneBeee** [comment]
> Strange, what version of skript do you use?

I was testing on Skript 2.2dev36 with Sk-NBeeT 2.9.0

**Comment by Spartan9802** [comment]
I think it comes from skript so, this doesn't work for me too
`
command /test:
	trigger:
	
		send "Work %item-nbt of player's tool%"
		
		set {_tool} to player's tool
		send "Dont Work %item-nbt of {_tool}%"
`

**Comment by ShaneBeee** [comment]
That is quite odd it wouldn't work on that version, as this plugin isn't really Skript version dependant. My only suggestion would be updating to Skript 2.2dev36 (the last working version for 1.8.8)... other than that, I don't know what else to tell ya, since I can not replicate the issue.

**Comment by Spartan9802** [comment]
I can't use dev36 at all because my skript server doesn't recognize the example and it generates an error in the console.

**Comment by ShaneBeee** [comment]
I'm not really sure what to tell ya then, I can't fix what ain't broken. And as far as I can see, there is nothing broken, since its working totally fine for me.

**Comment by Spartan9802** [comment]
I found where the problem comes from, Skript dev36 is not compatible with SkQuery, my problem is solved I switched to dev36 if it can help someone ^^
Thank you for your help! :)
