### ISSUE TITLE
Skript: give player a Mendign book?

### ISSUE THREAD

**Issue by Tyberhertz** [ShaneBeee/Sk-NBeeT#23]
how do i give a player a mending book in Skript?

maybe if I give the player an enchanted book with the corresponding NBT data?

`add "{Enchantments:[{id:""mending""}]}" to nbt of {_item}`

I would be happy if there is a possibility ..

**Comment by ShaneBeee** [comment]
Books are not enchanted, they have what is called stored enchantments.
I recommend grabbing one out of creative inventory, and checking the NBT of it so you can see how its done.
