### ISSUE TITLE
Reseting NBT no longer works after the big rewrite

### ISSUE THREAD

**Issue by Til0mi** [ShaneBeee/Sk-NBeeT#3]
After the rewrite reseting nbt of entity, block or item no longer works.

on 1.2.4:
![2019-03-04_09 13 17](https://user-images.githubusercontent.com/42693191/53716742-8c1bf080-3e5e-11e9-8ce1-bdf509c79588.png)

on 2.0.2:
![2019-03-04_09 15 32](https://user-images.githubusercontent.com/42693191/53716758-9b9b3980-3e5e-11e9-9c7b-730810dc7dc2.png)

My Minecraft version is 1.13.2, Skript 2.3.6 and server is the latest Paper Spigot.
Seems there might be a conflict with databases.

**Comment by ShaneBeee** [comment]
Yep, that is totally my fault.
Thank you for reporting it, I will start working on a fix right away.

**Comment by ShaneBeee** [comment]
This has now been fixed
https://github.com/ShaneBeee/Sk-NBeeT/releases/tag/2.0.3
