### ISSUE TITLE
Way to make none ops place custom NBT spawners

### ISSUE THREAD

**Issue by zmolahah** [ShaneBeee/Sk-NBeeT#4]
This isn't really your issue this is actually a problem in vanilla minecraft, I made a post on spigot here:
https://www.spigotmc.org/threads/people-who-arent-op-can-only-place-pig-spawners.362707/

And then I found this from md_5 stating that this a prevention in vanilla minecraft:
https://www.spigotmc.org/threads/how-do-i-allow-players-to-use-nbt-items-ctrl-middleclick.210013/

This is the part of my code that I had to actually force the server to make the player an op and then deop them just to get this to work:

```
place of monster spawner:
  op player
  if player's tool is mob spawner:
    set {_tool} to player's tool
    set name of {_tool} to "rem"
    delete lore of {_tool}
    set {_nbt} to nbt of {_tool}
    set {_mobid} to tag "BlockEntityTag" of {_nbt}
    set {_mobid} to tag "SpawnPotentials" of {_mobid}
    replace all "[{Entity:{id:""" with "" in {_mobid}
    replace all """},Weight:1}]" with "" in {_mobid}
    lore of tool of player is set
    set {_lore::*} to lore of tool of player
    loop {_lore::*}:
      if loop-value contains "&r&r&r&r&r&r":
        set nbt of block to "{MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnCount:0,SpawnData:{id:""%{_mobid}%""},MaxSpawnDelay:10000,Delay:10000,x:%x coord of block%,y:%y coord of block%,z:%z coord of block%,id:""minecraft:mob_spawner"",SpawnRange:0,MinSpawnDelay:10000,SpawnPotentials:[{Entity:{id:""%{_mobid}%""},Weight:1}]}"
        deop player
        stop
  else:
    set {_tool} to slot 40 of player
    set name of {_tool} to "rem"
    delete lore of {_tool}
    set {_nbt} to nbt of {_tool}
    lore of slot 40 of player is set
    set {_lore::*} to lore of slot 40 of player
    loop {_lore::*}:
      if loop-value contains "&r&r&r&r&r&r":
        set nbt of block to "{MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnCount:0,SpawnData:{id:""%{_mobid}%""},MaxSpawnDelay:10000,Delay:10000,x:%x coord of block%,y:%y coord of block%,z:%z coord of block%,id:""minecraft:mob_spawner"",SpawnRange:0,MinSpawnDelay:10000,SpawnPotentials:[{Entity:{id:""%{_mobid}%""},Weight:1}]}"
        deop player
        stop
  replace all "{BlockEntityTag:" with "" in {_nbt}
  replace all ",display:{Name:""{\""text\"":\""rem\""}""}" with "" in {_nbt}
  set {_nbt_length} to length of {_nbt}
  set {_nbt} to subtext of {_nbt} from characters 1 to ({_nbt_length} - 1)
  set nbt of block to {_nbt}
  deop player
```

I understand this is a problem in vanilla and not with your plugin but when I attempt to use the set nbt of block effect in the place event it still has this problem where it works fine if you are an op but not if you are a normal player so does the effect seem to take into account the player in the place event? And if so is there anyway you can make some sort of change so that it doesn't? So it's like the server is setting the nbt? I'm not really sure how it works.

**Comment by ShaneBeee** [comment]
The player should have nothing to do with this, since it is Skript that is dealing with the NBT not the player. 
From the little bit of testing I have done, setting the NBT of a block never seems to work out. 
My suggestion would be adding to the NBT of the block.

Here is a script I did a while back, take a look at it to give you a better understanding of how you can do it.
[**SpawnerStack**](https://forums.skunity.com/resources/spawnerstack.643/)

**Comment by zmolahah** [comment]
the code I use does work for me if I am op, but sure I'll check it out

**Comment by ShaneBeee** [comment]
> the code I use does work for me if I am op, but sure I'll check it out

That is so odd that it would do that. Honestly I have no clue what would be causing an issue like that since the player themselves is not directly changing the NBT of the block itself. 

Im going to close this issue for now as this doesn't seem to be an issue with this plugin but rather some weird issue with Spigot itself.

**Comment by zmolahah** [comment]
yeah I just tested this:
```
place of monster spawner:
  if player's tool is mob spawner:
    set {_tool} to player's tool
    set name of {_tool} to "rem"
    delete lore of {_tool}
    set {_nbt} to nbt of {_tool}
    set {_mobid} to tag "BlockEntityTag" of {_nbt}
    set {_mobid} to tag "SpawnPotentials" of {_mobid}
    replace all "[{Entity:{id:""" with "" in {_mobid}
    replace all """},Weight:1}]" with "" in {_mobid}
    lore of tool of player is set
    set {_lore::*} to lore of tool of player
    loop {_lore::*}:
      if loop-value contains "&r&r&r&r&r&r":
        add "{MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnCount:0,SpawnData:{id:""%{_mobid}%""},MaxSpawnDelay:10000,Delay:10000,x:%x coord of block%,y:%y coord of block%,z:%z coord of block%,id:""minecraft:mob_spawner"",SpawnRange:0,MinSpawnDelay:10000,SpawnPotentials:[{Entity:{id:""%{_mobid}%""},Weight:1}]}" to nbt of block
        stop
  else:
    set {_tool} to slot 40 of player
    set name of {_tool} to "rem"
    delete lore of {_tool}
    set {_nbt} to nbt of {_tool}
    lore of slot 40 of player is set
    set {_lore::*} to lore of slot 40 of player
    loop {_lore::*}:
      if loop-value contains "&r&r&r&r&r&r":
        add "{MaxNearbyEntities:0,RequiredPlayerRange:0,SpawnCount:0,SpawnData:{id:""%{_mobid}%""},MaxSpawnDelay:10000,Delay:10000,x:%x coord of block%,y:%y coord of block%,z:%z coord of block%,id:""minecraft:mob_spawner"",SpawnRange:0,MinSpawnDelay:10000,SpawnPotentials:[{Entity:{id:""%{_mobid}%""},Weight:1}]}" to nbt of block
        stop
  replace all "{BlockEntityTag:" with "" in {_nbt}
  replace all ",display:{Name:""{\""text\"":\""rem\""}""}" with "" in {_nbt}
  set {_nbt_length} to length of {_nbt}
  set {_nbt} to subtext of {_nbt} from characters 1 to ({_nbt_length} - 1)
  add {_nbt} to nbt of block
```
and adding nbt to the block instead of setting does work without requiring op, also it's not an issue with spigot md_5 has stated it's actually a thing in vanilla minecraft

**Comment by ShaneBeee** [comment]
> and adding nbt to the block instead of setting does work without requiring op
Well YAY for getting that to work. I remember doing some testing one time and "setting" NBT of a block was just not having it but "adding" to the NBT made things work.

> also it's not an issue with spigot md_5 has stated it's actually a thing in vanilla minecraft
Good to know
