### ISSUE TITLE
condition with nbt

### ISSUE THREAD

**Issue by Diclo** [ShaneBeee/Sk-NBeeT#5]
not work?

if command /nbt2:
  trigger:
    if player has 1 paper with nbt "{ench:[{lvl:3s,id:2s},{lvl:3s,id:5s}],HideFlags:33,display:{Name:""§e§lPase entre Dimensiones"",Lore:[""§7Se utiliza como ticket para viajar"",""§7en globo a otras islas en las lejanias"",""§7del Vacio.""]}}":
      send "si"
    else:
      send "no"

why do you always answer no and skstuff does not work in spigot-1.13.2.
Sorry for the inconvenience and in advance thank you.

**Comment by ShaneBeee** [comment]
It might be due to the NBT of the item not matching exactly.
My suggestion would be to hold the item in your hand and do
```vb
send "NBT: %nbt of player's tool%"
```
just to see what it outputs, and then confirm that they are exactly the same.

**Comment by Diclo** [comment]
very very, thank you
its work!

**Comment by ShaneBeee** [comment]
You're welcome
Sometimes what we THINK would be the NBT is not actually what it is. 
I always verify by checking the NBT of the tool
