### ISSUE TITLE
Unable to Add CustomName Tag

### ISSUE THREAD

**Issue by Wealthyturtle** [ShaneBeee/Sk-NBeeT#6]
Skript Version: 2.4-beta4
Server Version: Spigot 1.14.3
Sk-NBeeT Version: 2.4.1

Skripts:
```
on damage:
    set {_m} to victim
    add "{CustomNameVisible:1}" to {_m}'s entity-nbt
    add "{CustomName:test}" to {_m}'s entity-nbt
    send victim's display name to attacker
    send {_m}'s entity-nbt to attacker
```

```
on damage:
    set {_m} to victim
    add "{CustomNameVisible:1}" to {_m}'s entity-nbt
    add "{CustomName:""test""}" to {_m}'s entity-nbt
    send victim's display name to attacker
    send {_m}'s entity-nbt to attacker
```
Tried both skripts pasted above, the victim's display name is not sent, and the entity-nbt is also not sent due to the exception as detailed in the error

Console Skript Error: https://pastebin.com/KdxbfAXW

**Comment by ShaneBeee** [comment]
Thats because the NBT Tag is wrong

**Comment by Wealthyturtle** [comment]
Oops, my bad. Should have been ```""\""[insert]\""""```
