### ISSUE TITLE
SK-NBeet affecting condition "player's name" on events

### ISSUE THREAD

**Issue by aescraftbr** [ShaneBeee/Sk-NBeeT#7]
I had to change from 

```
on event:
  if player's name is "Admin":
```

to 

```
on event:
  if event-player is "Admin":
```

This happened after I installed SK-NBeet.

So it seems it affects the "players name" on event, and render it useless.
I think this should be fixed, as it may break skripts.

INFO:
craftbukkit git-spigot-1981d55-3e7b386 mc 1.14.4
Skript 2.4-beta5
skript-mirror 1.0.0
skquery 4.1.1
skrayfall 1.9.17
reqn 1.2.3
Sk-NBeet 
coreprotect
worldedit
protocolsupport
zpermissions

**Comment by ShaneBeee** [comment]
Thanks for letting me know, I will get a fix out for this soon.

**Comment by aescraftbr** [comment]
No problem.

Just updating: 
Seems like its affecting command as well.
For example, this command:

```
command /aescoincreate:
	trigger:
		if player's name is "Suti":
			give 64 sunflower of unbreaking 1 named "§6AesCoin" with lore "&eLastreado em Ouro" to player
		message "not suti"
```

Nickname is Suti but it wont detect.

**Comment by ShaneBeee** [comment]
Its an issue with anything named, I wrote the expression wrong which in turn overrides Skript's naming conventions

**Comment by ShaneBeee** [comment]
This should now be fixed!
